language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer --prefer-source install

script:
  - phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
