language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer --prefer-source install
  - composer require -n satooshi/php-coveralls:dev-master

script:
  - phpunit --coverage-text --coverage-clover build/logs/clover.xml

matrix:
  allow_failures:
    - php: hhvm

after_success:
  - php vendor/bin/coveralls -v
